-- vmate initial schema.
-- All timestamps are stored as RFC3339 strings with millisecond precision
-- in UTC (e.g. 2026-08-01T10:22:33.123Z), generated by strftime in SQLite.

CREATE TABLE IF NOT EXISTS configs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    path TEXT NOT NULL UNIQUE,
    path_sha256 TEXT NOT NULL,

    remote_host TEXT,

    country TEXT NOT NULL DEFAULT 'UNKNOWN',
    country_source TEXT NOT NULL DEFAULT 'unknown',

    status TEXT NOT NULL DEFAULT 'unknown'
        CHECK (status IN ('unknown', 'success', 'failed')),

    success_count INTEGER NOT NULL DEFAULT 0,
    failure_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,

    last_success_at TEXT,
    last_failure_at TEXT,
    last_skipped_at TEXT,

    last_error TEXT,

    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_configs_country
    ON configs(country);

CREATE INDEX IF NOT EXISTS idx_configs_status_country
    ON configs(status, country);

CREATE INDEX IF NOT EXISTS idx_configs_last_success
    ON configs(last_success_at DESC);

CREATE TABLE IF NOT EXISTS ip_country_cache (
    ip TEXT PRIMARY KEY,
    country TEXT NOT NULL,
    fetched_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    config_id INTEGER REFERENCES configs(id) ON DELETE CASCADE,
    kind TEXT NOT NULL,
    message TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_events_config_id
    ON events(config_id);
